#!/usr/bin/env python3

import sys

def fibonacci():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

def main():
    for i in fibonacci():
        try:
            print(i)
        except BrokenPipeError:
            break

if __name__ == '__main__':
    sys.stderr = None
    main()
