#!/usr/bin/env python3

import sys

def main(lines):
    total = sum(map(int, lines))
    try:
        print(total)
    except BrokenPipeError:
        pass

if __name__ == '__main__':
    main(sys.stdin)
